export type WineType = "Tinto" | "Branco" | "Rosé" | "Espumante";

export type Wine = {
  id: string;
  nome: string;
  produtor: string;
  safra: number;
  regiao: string;
  pais: string;
  tipo: WineType;
  uva: string;
  nota: number;
  avaliacoes: number;
  preco: number;
  imagem: string;
  sabores: string[];
  harmonizacao: string[];
  descricao: string;
};

export const wines: Wine[] = [
  {
    id: "alma-negra-misterio",
    nome: "Alma Negra Misterio I",
    produtor: "Ernesto Catena",
    safra: 2021,
    regiao: "Mendoza",
    pais: "Argentina",
    tipo: "Tinto",
    uva: "Malbec / Bonarda",
    nota: 4.4,
    avaliacoes: 14209,
    preco: 199,
    imagem: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=600&auto=format&fit=crop&q=80",
    sabores: ["Ameixa madura", "Baunilha", "Especiarias", "Madeira tostada"],
    harmonizacao: ["Carnes vermelhas", "Churrasco", "Massas ao ragu"],
    descricao: "Um vinho misterioso e cativante criado por Ernesto Catena. Apresenta notas intensas de frutas vermelhas e negras, com um toque elegante de carvalho."
  },
  {
    id: "catena-malbec",
    nome: "Catena Malbec",
    produtor: "Catena Zapata",
    safra: 2022,
    regiao: "Mendoza",
    pais: "Argentina",
    tipo: "Tinto",
    uva: "Malbec",
    nota: 4.3,
    avaliacoes: 28401,
    preco: 249,
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    sabores: ["Frutas negras", "Amora", "Chocolate", "Café"],
    harmonizacao: ["Churrasco", "Carnes vermelhas", "Queijos maduros"],
    descricao: "Um dos Malbecs mais emblemáticos do mundo. Produzido a partir de uvas cultivadas em altitudes elevadas, oferece grande concentração e elegância."
  },
  {
    id: "angelica-zapata-cab-franc",
    nome: "Angélica Zapata Cabernet Franc Alta",
    produtor: "Catena Zapata",
    safra: 2019,
    regiao: "Mendoza",
    pais: "Argentina",
    tipo: "Tinto",
    uva: "Cabernet Franc",
    nota: 4.7,
    avaliacoes: 8432,
    preco: 389,
    imagem: "https://images.unsplash.com/photo-1628853347101-9252efbe3a81?w=600&auto=format&fit=crop&q=80",
    sabores: ["Cassis", "Eucalipto", "Pimenta preta", "Tostado"],
    harmonizacao: ["Cordeiro", "Filé mignon", "Massas ao ragu"],
    descricao: "Vinho varietal de produção limitada. Envelhecido em barricas francesas, exibe aroma complexo de frutas vermelhas e especiarias com final persistente."
  },
  {
    id: "dv-catena-cab-malbec",
    nome: "DV Catena Cabernet-Malbec",
    produtor: "Catena Zapata",
    safra: 2021,
    regiao: "Mendoza",
    pais: "Argentina",
    tipo: "Tinto",
    uva: "Cabernet Sauvignon / Malbec",
    nota: 4.2,
    avaliacoes: 19821,
    preco: 189,
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&auto=format&fit=crop&q=80",
    sabores: ["Cereja preta", "Pimenta", "Tabaco", "Estruturado"],
    harmonizacao: ["Churrasco", "Carnes vermelhas", "Queijos curados"],
    descricao: "Blend clássico argentino. O Cabernet Sauvignon aporta estrutura e taninos firmes, enquanto o Malbec contribui com suavidade e notas de frutas maduras."
  },
  {
    id: "casillero-cab-sauvignon",
    nome: "Casillero del Diablo Reserva Cabernet Sauvignon",
    produtor: "Concha y Toro",
    safra: 2022,
    regiao: "Vale Central",
    pais: "Chile",
    tipo: "Tinto",
    uva: "Cabernet Sauvignon",
    nota: 3.6,
    avaliacoes: 52402,
    preco: 59,
    imagem: "https://images.unsplash.com/photo-1629019725048-776e11c3855c?w=600&auto=format&fit=crop&q=80",
    sabores: ["Ameixa", "Cereja fresca", "Baunilha", "Fácil de beber"],
    harmonizacao: ["Queijos maduros", "Carnes vermelhas", "Aperitivos"],
    descricao: "O vinho mais conhecido do Chile. Destaca-se por seus aromas de cereja, ameixas e toques sutis de baunilha provenientes de seu envelhecimento em carvalho."
  },
  {
    id: "montes-alpha-cabernet",
    nome: "Montes Alpha Cabernet Sauvignon",
    produtor: "Montes",
    safra: 2021,
    regiao: "Vale de Colchagua",
    pais: "Chile",
    tipo: "Tinto",
    uva: "Cabernet Sauvignon",
    nota: 4.1,
    avaliacoes: 12431,
    preco: 229,
    imagem: "https://images.unsplash.com/photo-1553122912-78d91b7c09db?w=600&auto=format&fit=crop&q=80",
    sabores: ["Cassis maduro", "Cacau", "Pimenta vermelha", "Tabaco"],
    harmonizacao: ["Cordeiro", "Churrasco", "Filé mignon"],
    descricao: "Um pioneiro entre os vinhos premium chilenos. Apresenta corpo generoso, taninos macios e um final refinado e muito elegante."
  },
  {
    id: "cartuxa-colheita-tinto",
    nome: "Cartuxa Colheita Alentejo",
    produtor: "Fundação Eugénio de Almeida",
    safra: 2019,
    regiao: "Alentejo",
    pais: "Portugal",
    tipo: "Tinto",
    uva: "Aragonez / Alicante Bouschet / Trincadeira",
    nota: 4.4,
    avaliacoes: 10403,
    preco: 449,
    imagem: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=600&auto=format&fit=crop&q=80",
    sabores: ["Fruta madura", "Silvestre", "Elegante", "Especiarias doces"],
    harmonizacao: ["Carnes vermelhas", "Queijos curados", "Massas ao ragu"],
    descricao: "Vinho clássico alentejano. É encorpado, com boa acidez e taninos firmes, combinando notas de frutas vermelhas e toques de envelhecimento em madeira."
  },
  {
    id: "esporao-reserva-tinto",
    nome: "Esporão Reserva Alentejo DOC",
    produtor: "Herdade do Esporão",
    safra: 2021,
    regiao: "Alentejo",
    pais: "Portugal",
    tipo: "Tinto",
    uva: "Alicante Bouschet / Trincadeira / Aragonez",
    nota: 4.2,
    avaliacoes: 15432,
    preco: 299,
    imagem: "https://images.unsplash.com/photo-1603178455924-ef33372953bb?w=600&auto=format&fit=crop&q=80",
    sabores: ["Compota de frutas", "Especiarias", "Cacau", "Taninos ricos"],
    harmonizacao: ["Churrasco", "Queijos maduros", "Massas ao ragu"],
    descricao: "Um grande clássico do Alentejo. Produzido com técnicas orgânicas, oferece um paladar estruturado, denso e repleto de complexidade."
  },
  {
    id: "pera-manca-tinto",
    nome: "Pêra-Manca Alentejo Tinto",
    produtor: "Fundação Eugénio de Almeida",
    safra: 2015,
    regiao: "Alentejo",
    pais: "Portugal",
    tipo: "Tinto",
    uva: "Aragonez / Trincadeira",
    nota: 4.9,
    avaliacoes: 2190,
    preco: 3900,
    imagem: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=600&auto=format&fit=crop&q=80",
    sabores: ["Complexo", "Frutas secas", "Couro", "Final monumental"],
    harmonizacao: ["Cordeiro", "Filé mignon", "Queijos azuis"],
    descricao: "O vinho mais cultuado de Portugal. Produzido apenas em anos de qualidade excepcional, apresenta enorme longevidade e riqueza aromática indescritível."
  },
  {
    id: "brunello-banfi",
    nome: "Brunello di Montalcino DOCG",
    produtor: "Banfi",
    safra: 2018,
    regiao: "Toscana",
    pais: "Itália",
    tipo: "Tinto",
    uva: "Sangiovese",
    nota: 4.5,
    avaliacoes: 9811,
    preco: 890,
    imagem: "https://images.unsplash.com/photo-1628853347101-9252efbe3a81?w=600&auto=format&fit=crop&q=80",
    sabores: ["Alcaçuz", "Cereja preta", "Tabaco", "Acidez vibrante"],
    harmonizacao: ["Massas ao ragu", "Cordeiro", "Queijos curados"],
    descricao: "Vinho de classe mundial da Toscana. Elaborado 100% com uvas Sangiovese Grosso, envelhece no mínimo 4 anos antes de ir ao mercado."
  },
  {
    id: "barolo-pio-cesare",
    nome: "Barolo DOCG",
    produtor: "Pio Cesare",
    safra: 2018,
    regiao: "Piemonte",
    pais: "Itália",
    tipo: "Tinto",
    uva: "Nebbiolo",
    nota: 4.6,
    avaliacoes: 4103,
    preco: 980,
    imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    sabores: ["Rosas", "Alcatrão", "Framboesa silvestre", "Taninos potentes"],
    harmonizacao: ["Cordeiro", "Filé mignon", "Queijos maduros"],
    descricao: "O 'Rei dos Vinhos'. Um Barolo tradicional, de grande estrutura, elegância e complexidade, com potencial de guarda extraordinário."
  },
  {
    id: "guigal-cotes-rhone",
    nome: "Côtes du Rhône Rouge",
    produtor: "E. Guigal",
    safra: 2020,
    regiao: "Vale do Rhône",
    pais: "França",
    tipo: "Tinto",
    uva: "Syrah / Grenache / Mourvèdre",
    nota: 3.9,
    avaliacoes: 32044,
    preco: 189,
    imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&auto=format&fit=crop&q=80",
    sabores: ["Ameixa preta", "Pimenta", "Garrigue", "Equilibrado"],
    harmonizacao: ["Churrasco", "Frango grelhado", "Massas ao ragu"],
    descricao: "Um clássico francês indiscutível. Elaborado pela prestigiosa casa Guigal, oferece frutas escuras combinadas com um toque picante típico da Syrah."
  },
  {
    id: "chateau-talbot",
    nome: "Château Talbot Saint-Julien Grand Cru Classé",
    produtor: "Château Talbot",
    safra: 2017,
    regiao: "Bordeaux",
    pais: "França",
    tipo: "Tinto",
    uva: "Cabernet Sauvignon / Merlot / Petit Verdot",
    nota: 4.4,
    avaliacoes: 6310,
    preco: 1290,
    imagem: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=600&auto=format&fit=crop&q=80",
    sabores: ["Cassis", "Grafite", "Cedro", "Taninos de veludo"],
    harmonizacao: ["Filé mignon", "Cordeiro", "Queijos azuis"],
    descricao: "Grande clássico de Bordeaux (St-Julien). Combina estrutura impecável, finesse e aromas profundos de frutas escuras e especiarias."
  },
  {
    id: "gran-enemigo-gualtallary",
    nome: "Gran Enemigo Single Vineyard Gualtallary",
    produtor: "Bodega Aleanna",
    safra: 2018,
    regiao: "Mendoza",
    pais: "Argentina",
    tipo: "Tinto",
    uva: "Cabernet Franc / Malbec",
    nota: 4.8,
    avaliacoes: 7891,
    preco: 789,
    imagem: "https://images.unsplash.com/photo-1629019725048-776e11c3855c?w=600&auto=format&fit=crop&q=80",
    sabores: ["Tiza", "Cereja ácida", "Herbáceo", "Mineral"],
    harmonizacao: ["Cordeiro", "Carnes vermelhas", "Massas ao ragu"],
    descricao: "Vinho de pontuação lendária criado pelo enólogo Alejandro Vigil. Muito profundo e mineral, com uma energia única proveniente do terroir de Gualtallary."
  },
  {
    id: "leyda-pinot-noir",
    nome: "Leyda Reserva Pinot Noir",
    produtor: "Viña Leyda",
    safra: 2022,
    regiao: "Vale de Leyda",
    pais: "Chile",
    tipo: "Tinto",
    uva: "Pinot Noir",
    nota: 3.8,
    avaliacoes: 4210,
    preco: 99,
    imagem: "https://images.unsplash.com/photo-1553122912-78d91b7c09db?w=600&auto=format&fit=crop&q=80",
    sabores: ["Morango", "Cereja vermelha", "Toque de ervas", "Leve"],
    harmonizacao: ["Peixes grelhados", "Frango grelhado", "Saladas"],
    descricao: "Um Pinot Noir de clima marítimo fresco. Muito leve, fresco, com acidez brilhante e aromas puros de frutas vermelhas silvestres."
  },
  {
    id: "cloudy-bay-sauv-blanc",
    nome: "Cloudy Bay Sauvignon Blanc",
    produtor: "Cloudy Bay",
    safra: 2023,
    regiao: "Marlborough",
    pais: "Nova Zelândia",
    tipo: "Branco",
    uva: "Sauvignon Blanc",
    nota: 4.4,
    avaliacoes: 19876,
    preco: 299,
    imagem: "https://images.unsplash.com/photo-1569534969245-862296b9ac17?w=600&auto=format&fit=crop&q=80",
    sabores: ["Maracujá", "Groselha espinhosa", "Limão", "Mineralidade cortante"],
    harmonizacao: ["Peixes grelhados", "Frutos do mar", "Ostras"],
    descricao: "A referência mundial da Sauvignon Blanc. Exibe aromas extremamente expressivos e tropicais, com uma boca vibrante e cheia de frescor."
  },
  {
    id: "catena-chardonnay",
    nome: "Catena Chardonnay",
    produtor: "Catena Zapata",
    safra: 2022,
    regiao: "Mendoza",
    pais: "Argentina",
    tipo: "Branco",
    uva: "Chardonnay",
    nota: 4.1,
    avaliacoes: 9842,
    preco: 179,
    imagem: "https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?w=600&auto=format&fit=crop&q=80",
    sabores: ["Maçã verde", "Pêssego", "Manteiga", "Toque mineral"],
    harmonizacao: ["Frango grelhado", "Peixes grelhados", "Queijos maduros"],
    descricao: "Chardonnay elegante de alta montanha. Apresenta acidez fresca equilibrada por notas de frutas cítricas, de caroço e toques sutis de baunilha."
  },
  {
    id: "casillero-sauv-blanc",
    nome: "Casillero del Diablo Sauvignon Blanc",
    produtor: "Concha y Toro",
    safra: 2023,
    regiao: "Vale Central",
    pais: "Chile",
    tipo: "Branco",
    uva: "Sauvignon Blanc",
    nota: 3.5,
    avaliacoes: 14210,
    preco: 59,
    imagem: "https://images.unsplash.com/photo-1569534969245-862296b9ac17?w=600&auto=format&fit=crop&q=80",
    sabores: ["Limão-siciliano", "Pêssego branco", "Fresco", "Leve"],
    harmonizacao: ["Saladas", "Aperitivos", "Frutos do mar"],
    descricao: "Vinho branco leve e muito refrescante, com aromas cítricos de limão e pêssego, ideal para dias quentes e pratos leves."
  },
  {
    id: "esporao-reserva-branco",
    nome: "Esporão Reserva Branco Alentejo",
    produtor: "Herdade do Esporão",
    safra: 2022,
    regiao: "Alentejo",
    pais: "Portugal",
    tipo: "Branco",
    uva: "Antão Vaz / Arinto / Roupeiro",
    nota: 4.1,
    avaliacoes: 6310,
    preco: 199,
    imagem: "https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?w=600&auto=format&fit=crop&q=80",
    sabores: ["Toranja", "Tangerina", "Nota de nozes", "Untuoso"],
    harmonizacao: ["Peixes grelhados", "Frutos do mar", "Frango grelhado"],
    descricao: "Um branco alentejano encorpado e envelhecido parcialmente em barricas. Oferece textura rica de frutas cítricas e secas com ótima acidez."
  },
  {
    id: "whispering-angel",
    nome: "Whispering Angel Rosé Côtes de Provence",
    produtor: "Château d'Esclans",
    safra: 2022,
    regiao: "Provence",
    pais: "França",
    tipo: "Rosé",
    uva: "Grenache / Cinsault / Rolle",
    nota: 4.3,
    avaliacoes: 24102,
    preco: 329,
    imagem: "https://images.unsplash.com/photo-1594142416766-3d231b54a014?w=600&auto=format&fit=crop&q=80",
    sabores: ["Morango fresco", "Pêssego vermelho", "Cítrico leve", "Seco"],
    harmonizacao: ["Aperitivos", "Sushi", "Saladas"],
    descricao: "O rosé mais famoso do mundo. É incrivelmente pálido, delicado, seco e fresco no paladar, com notas sutis de frutas vermelhas frescas."
  },
  {
    id: "mateus-rose",
    nome: "Mateus Rosé Original",
    produtor: "Sogrape Vinhos",
    safra: 2023,
    regiao: "Várias Regiões",
    pais: "Portugal",
    tipo: "Rosé",
    uva: "Baga / Rufete / Bastardo",
    nota: 3.5,
    avaliacoes: 48900,
    preco: 69,
    imagem: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=600&auto=format&fit=crop&q=80",
    sabores: ["Adocicado leve", "Fruta vermelha", "Fruity", "Frisante leve"],
    harmonizacao: ["Aperitivos", "Sushi", "Sobremesas leves"],
    descricao: "Vinho rosé frisante de enorme sucesso mundial. Levemente efervescente e muito fácil de beber, com aromas frutados jovens."
  },
  {
    id: "veuve-clicquot-brut",
    nome: "Veuve Clicquot Ponsardin Champagne Yellow Label",
    produtor: "Veuve Clicquot",
    safra: 2019,
    regiao: "Champagne",
    pais: "França",
    tipo: "Espumante",
    uva: "Pinot Noir / Chardonnay / Pinot Meunier",
    nota: 4.5,
    avaliacoes: 78103,
    preco: 499,
    imagem: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80",
    sabores: ["Pão tostado", "Maçã assada", "Cremoso", "Perlage abundante"],
    harmonizacao: ["Ostras", "Caviar", "Aperitivos"],
    descricao: "Ícone mundial de comemoração. A famosa 'Etiqueta Amarela' define o estilo da casa, equilibrando força, frescor, riqueza aromática e cremosidade."
  },
  {
    id: "moet-chandon-imperial",
    nome: "Moët & Chandon Impérial Brut Champagne",
    produtor: "Moët & Chandon",
    safra: 2020,
    regiao: "Champagne",
    pais: "França",
    tipo: "Espumante",
    uva: "Pinot Noir / Pinot Meunier / Chardonnay",
    nota: 4.4,
    avaliacoes: 84091,
    preco: 469,
    imagem: "https://images.unsplash.com/photo-1613090288863-7186fb6c085b?w=600&auto=format&fit=crop&q=80",
    sabores: ["Pera", "Pêssego", "Brioche", "Muito elegante"],
    harmonizacao: ["Ostras", "Frutos do mar", "Sushi"],
    descricao: "O champagne mais vendido do mundo. Exibe um aroma brilhante de frutas de polpa branca, nuances de cereais e brioche com perlage fina."
  },
  {
    id: "freixenet-cordon-negro",
    nome: "Freixenet Cordon Negro Cava Brut",
    produtor: "Freixenet",
    safra: 2022,
    regiao: "Cava",
    pais: "Espanha",
    tipo: "Espumante",
    uva: "Macabeo / Xarel-lo / Parellada",
    nota: 3.8,
    avaliacoes: 29011,
    preco: 99,
    imagem: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&auto=format&fit=crop&q=80",
    sabores: ["Maçã", "Pera cítrica", "Refrescante", "Bolha fina"],
    harmonizacao: ["Aperitivos", "Sushi", "Frutos do mar"],
    descricao: "Um Cava clássico espanhol em sua garrafa preta emblemática. Muito refrescante e limpo, com perlage viva e aroma frutado sutil."
  },
  {
    id: "chandon-passion",
    nome: "Chandon Passion Demi-Sec",
    produtor: "Chandon Brasil",
    safra: 2022,
    regiao: "Serra Gaúcha",
    pais: "Brasil",
    tipo: "Espumante",
    uva: "Malvasia de Cândia / Moscato Canelli / Pinot Noir",
    nota: 4.2,
    avaliacoes: 8200,
    preco: 109,
    imagem: "https://images.unsplash.com/photo-1613090288863-7186fb6c085b?w=600&auto=format&fit=crop&q=80",
    sabores: ["Maracujá", "Pêssego", "Adocicado refrescante", "Rosado"],
    harmonizacao: ["Sobremesas leves", "Aperitivos", "Sushi"],
    descricao: "Desenvolvido especialmente para o paladar brasileiro. Apresenta cor rosada moderna, aromas exóticos de maracujá, lichia e pêssego com final refrescante."
  }
];

export const regioes = [
  { nome: "Mendoza", pais: "Argentina", imagem: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600" },
  { nome: "Alentejo", pais: "Portugal", imagem: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=600" },
  { nome: "Toscana", pais: "Itália", imagem: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600" },
  { nome: "Champagne", pais: "França", imagem: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600" }
];

export function getWine(id: string) {
  return wines.find((w) => w.id === id);
}
