/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AdegaRouteImport } from './routes/adega'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VinhoIdRouteImport } from './routes/vinho.$id'
import { Route as ScanResultadoRouteImport } from './routes/scan.resultado'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdegaRoute = AdegaRouteImport.update({
  id: '/adega',
  path: '/adega',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VinhoIdRoute = VinhoIdRouteImport.update({
  id: '/vinho/$id',
  path: '/vinho/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultadoRoute = ScanResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => ScanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adega': typeof AdegaRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/resultado': typeof ScanResultadoRoute
  '/vinho/$id': typeof VinhoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adega': typeof AdegaRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/resultado': typeof ScanResultadoRoute
  '/vinho/$id': typeof VinhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adega': typeof AdegaRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/perfil': typeof PerfilRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/resultado': typeof ScanResultadoRoute
  '/vinho/$id': typeof VinhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adega'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/home'
    | '/perfil'
    | '/scan'
    | '/scan/resultado'
    | '/vinho/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adega'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/home'
    | '/perfil'
    | '/scan'
    | '/scan/resultado'
    | '/vinho/$id'
  id:
    | '__root__'
    | '/'
    | '/adega'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/home'
    | '/perfil'
    | '/scan'
    | '/scan/resultado'
    | '/vinho/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdegaRoute: typeof AdegaRoute
  BuscaRoute: typeof BuscaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  PerfilRoute: typeof PerfilRoute
  ScanRoute: typeof ScanRouteWithChildren
  VinhoIdRoute: typeof VinhoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adega': {
      id: '/adega'
      path: '/adega'
      fullPath: '/adega'
      preLoaderRoute: typeof AdegaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vinho/$id': {
      id: '/vinho/$id'
      path: '/vinho/$id'
      fullPath: '/vinho/$id'
      preLoaderRoute: typeof VinhoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/resultado': {
      id: '/scan/resultado'
      path: '/resultado'
      fullPath: '/scan/resultado'
      preLoaderRoute: typeof ScanResultadoRouteImport
      parentRoute: typeof ScanRoute
    }
  }
}

interface ScanRouteChildren {
  ScanResultadoRoute: typeof ScanResultadoRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanResultadoRoute: ScanResultadoRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdegaRoute: AdegaRoute,
  BuscaRoute: BuscaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  PerfilRoute: PerfilRoute,
  ScanRoute: ScanRouteWithChildren,
  VinhoIdRoute: VinhoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
